#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# Example with runApplication:
# - runs blockMesh in background
# - redirecting standard output to log.blockMesh
# - does *not* run in log file already exists
./Allclean
runApplication blockMesh
runApplication checkMesh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite
#Modify in Region A
runApplication -overwrite foamDictionary   0/A/T  -entry boundaryField/A_to_B   -set "
  {
 type compressible::turbulentTemperatureCoupledBaffleMixed ;
Tnbr T;
kappa solidThermo;
kappaName none;
value uniform 300;}" 

runApplication -overwrite foamDictionary  0/A/T  -entry boundaryField/A_to_C   -set "
 {
 type compressible::turbulentTemperatureCoupledBaffleMixed ;
Tnbr T;
kappa solidThermo;
kappaName none;
value uniform 300;
 }" 

#Modify in Region B
runApplication -overwrite foamDictionary   0/B/T  -entry boundaryField/B_to_A   -set "
  {
 type compressible::turbulentTemperatureCoupledBaffleMixed ;
Tnbr T;
kappa solidThermo;
kappaName none;
value uniform 300;}" 

runApplication -overwrite foamDictionary  0/B/T  -entry boundaryField/B_to_C   -set "
 {
 type compressible::turbulentTemperatureCoupledBaffleMixed ;
Tnbr T;
kappa solidThermo;
kappaName none;
value uniform 300;
 }" 
#Modify in Region C
runApplication -overwrite foamDictionary   0/C/T  -entry boundaryField/C_to_B   -set "
  {
 type compressible::turbulentTemperatureCoupledBaffleMixed ;
Tnbr T;
kappa solidThermo;
kappaName none;
value uniform 300;}" 

runApplication -overwrite foamDictionary  0/C/T  -entry boundaryField/C_to_A   -set "
 {
 type compressible::turbulentTemperatureCoupledBaffleMixed ;
Tnbr T;
kappa solidThermo;
kappaName none;
value uniform 300;
 }" 


#runParallel "$(getApplication)"
#------------------------------------------------------------------------------
