#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# Example with runApplication:
# - runs blockMesh in background
# - redirecting standard output to log.blockMesh
# - does *not* run in log file already exists
./Allclean
runApplication blockMesh
runApplication checkMesh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite
my_array=(foo bar)

for i in "${my_array[@]}"; do echo "$i"; done

# foamDictionary   0/$i/T  -entry boundaryField/"$i"_to_"$i+1"   -set "
#  {
# type compressible::turbulentTemperatureCoupledBaffleMixed ;
#Tnbr T;
#kappa solidThermo;
#kappaName none;
#value uniform 300;}" 

# foamDictionary  0/A/T  -entry boundaryField/A_to_C   -set "
# {
# type compressible::turbulentTemperatureCoupledBaffleMixed ;
#Tnbr T;
#kappa solidThermo;
#kappaName none;
#value uniform 300;
# }" 


#runParallel "$(getApplication)"
#------------------------------------------------------------------------------
